version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "openainodejs"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1om3uv0w6o6gb"
s3_prefix = "openainodejs"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
